# Generated by Django 3.1.6 on 2024-07-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0004_auto_20230927_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preconstruction',
            options={'ordering': ('-status', '-last_updated')},
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
